# syntax=docker/dockerfile:1
FROM python:3.8-slim-buster

# docker pull jarredsumner/bun:edge
# docker run --rm --init --ulimit memlock=-1:-1 jarredsumner/bun:edge

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD [ "python3", "server.py"]